### ISSUE TITLE
Error using v0.2.2 w/ Node v0.10

### ISSUE THREAD

**Issue by pulkitsinghal** [GovRight/loopback-console#9]
```
loopback > 
/Users/pulkitsinghal/.nvm/v0.10.37/lib/node_modules/loopback-console/index.js:123
        throw(err);
              ^
TypeError: Cannot call method 'bind' of undefined
    at /Users/pulkitsinghal/.nvm/v0.10.37/lib/node_modules/loopback-console/repl.js:21:44
    at REPLServer.self.eval (repl.js:122:7)
    at Object.module.exports.start (/Users/pulkitsinghal/.nvm/v0.10.37/lib/node_modules/loopback-console/repl.js:19:16)
    at Object.module.exports.start (/Users/pulkitsinghal/.nvm/v0.10.37/lib/node_modules/loopback-console/index.js:96:21)
    at Object.module.exports.cli (/Users/pulkitsinghal/.nvm/v0.10.37/lib/node_modules/loopback-console/index.js:118:22)
    at Object.<anonymous> (/Users/pulkitsinghal/.nvm/v0.10.37/lib/node_modules/loopback-console/bin/loopback-console:3:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

**Comment by doublemarked** [comment]
closing this out - won't support 0.10.x
